name: JWT/JWE Encryption

on:
  push:
    branches:
    - master
    - 'release/**'
  pull_request:
    branches:
    - master
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    
    # Run unit test
    - name: Run testing
      run: go test -v -cover -coverprofile=coverage.out ./... -gcflags=all=-l

    # Upload coverage report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}